name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: "docker/Dockerfile"
          push: true
          tags: nikolinachorkovich/skillsandpills:latest

      # - name: copy composefile via ssh password
      #   uses: garygrossgarten/github-action-scp@release
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PRIVATE_KEY }}
      #     port: 22
      #     local: "docker/compose.yaml"
      #     remote: "compose.yaml"

  deploy:
    name: Deploy to Digital Ocean Droplet
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            # Stop all running Docker Containers
            docker kill $(docker ps -a)

            # Free up space
            docker system prune -a -f

            # Login to Docker Container Registry
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

            # Pull the Docker Image 
            docker pull ghcr.io/${{ github.repository }}:latest

            # Run a new container from a new image
            # docker run -d -p 80:8080 -p 443:443 -t ghcr.io/${{ github.repository }}:latest
            /usr/local/bin/docker-compose up -d